version: '3.6'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    ports:
      - ${NGINX_HOST_PORT}:80
    networks:
      - money-manager-network

  client:
    build:
      dockerfile: ./docker/client/Dockerfile
      context: .
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    volumes: 
      - ./client/.:/app
    ports:
      - ${CLIENT_HOST_PORT}:3000
    networks:
      - money-manager-network

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
      args:
        DOCKER_UID: ${DOCKER_UID:-0}
        DOCKER_GID: ${DOCKER_GID:-0}
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    volumes: 
      - ./api/.:/app
    networks:
      - money-manager-network

  redis:
    image: redis:7.0.7-alpine
    restart: always
    volumes:
      - redis-vol:/data
    ports:
      - ${REDIS_HOST_PORT}:6379
    networks:
      - money-manager-network


networks:
  money-manager-network:
    driver: bridge

volumes:
  redis-vol:
    driver: local
